name: compare-prod-and-stage-tags
description: Compare two tags between stage and prod releases. Error if they have source code changes.
inputs:
  prod_tag:  
    description: The prod tag to check
    required: true
  stage_tag:  
    description: The stage tag to check
    required: true
runs:
  using: "composite"
  steps:
  steps:
      - name: check prod tag existence
        id: check-prod-tag
        uses: delfidiagnotics/check-tag-existence@v1.0
        with:
          tag: ${{github.event.inputs.prod_tag}}
      - name: check stage tag existence
        id: check-stage-tag
        uses: delfidiagnotics/check-tag-existence@v1.0
        with:
          tag: ${{github.event.inputs.stage_tag}}
      - name: compare tags to show there was no differance between them
        id: diff-tags
        run: |
          echo "num_diffs=$(git diff ${{github.event.inputs.prod_tag}} ${{github.event.inputs.stage_tag}} --stat | wc -l | tr -d ' ')" >> "$GITHUB_OUTPUT"
      - name: evaluate tag diff
        if: (steps.diff-tags.outputs.num_diffs > 0)
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Cannot proceed. There were ${{steps.diff-tags.outputs.num_diffs}} changes between stage tag: ${{github.event.inputs.stage_tag}} and prod tag: ${{github.event.inputs.prod_tag}}')