name: compare-prod-and-stage-tags
description: Compare two tags between stage and prod releases. Error if they have source code changes.
inputs:
  prod_tag:  
    description: The prod tag to check
    required: true
  stage_tag:  
    description: The stage tag to check
    required: true
runs:
  using: "composite"
  steps:
      - name: Check prod tag existence
        id: check-prod-tag
        uses: delfidiagnostics/check-tag-existence@v1.1
        with:
          tag: ${{inputs.prod_tag}}
      - name: Check stage tag existence
        id: check-stage-tag
        uses: delfidiagnostics/check-tag-existence@v1.1
        with:
          tag: ${{inputs.stage_tag}}
      - name: Compare tags to show there was no differance between them
        id: diff-tags
        shell: bash
        run: |
          echo "num_diffs=$(git diff ${{inputs.prod_tag}} ${{inputs.stage_tag}} --stat | wc -l | tr -d ' ')" >> "$GITHUB_OUTPUT"
      - name: Evaluate tag diff
        if: (steps.diff-tags.outputs.num_diffs > 0)
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Cannot proceed. ${{steps.diff-tags.outputs.num_diffs}} changes between prod tag: ${{inputs.prod_tag}} and stage tag: ${{inputs.stage_tag}} ')